apiVersion: v2
name: nfs-client-provisioner0
description: Wrapper helm-chart for nfs-subdir-external-provisioner0
type: application
appVersion: 4.0.2
home: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
version: 4.0.13
kubeVersion: ">=1.9.0-0"
sources:
  - https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
keywords:
  - nfs
  - storage
  - provisioner

dependencies:
  - name: nfs-subdir-external-provisioner
    version: 4.0.13
    repository: "@nfs-subdir-external-provisioner"
