apiVersion: v2
version: 3.1.0
name: openebs
appVersion: 3.1.0
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - iSCSI
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
maintainers:
  - name: kmova
    email: kiran.mova@mayadata.io
  - name: prateekpandey14
    email: prateek.pandey@mayadata.io
  - name: shovanmaity
    email: shovan.maity@mayadata.io
dependencies:
  - name: openebs
    version: "3.1.0"
    repository: "https://openebs.github.io/charts"
