nfs-subdir-external-provisioner:
  storageClass:
    create: true
    name: "nfs-dynamic1"
  nfs:
    server: "172.26.11.66"
    path: "/nfs/dynamic"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
