vault-secrets-webhook:
  replicaCount: 1
  resources:
    limits:
      cpu: "150m"
      memory: "100Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"
  namespaceSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - kube-system
          - vswh
          - vault
