---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-defaultbackend
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/default-backend: nginx-ingress-defaultbackend
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: nginx-ingress-defaultbackend
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-defaultbackend
  namespace: ingress-nginx
spec:
  selector:
    app: nginx-ingress-defaultbackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-defaultbackend
  labels:
    app: nginx-ingress-defaultbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-defaultbackend
  template:
    metadata:
      labels:
        app: nginx-ingress-defaultbackend
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/defaultbackend-amd64:1.5
          ports:
            - containerPort: 8080
