apiVersion: v2
appVersion: "1.89.0-rc.1"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.89.0-rc.1
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
dependencies:
  - name: cost-analyzer
    version: 1.88.1
    repository: https://kubecost.github.io/cost-analyzer/
