---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-mongodb-0
  namespace: mongodb
spec:
  storageClassName: local-storage
  volumeName: datadir-mongodb-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mongodb-0
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  claimRef:
    name: datadir-mongodb-0
    namespace: mongodb
  local:
    path: /mnt/disks/mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-mongodb-1
  namespace: mongodb
spec:
  storageClassName: local-storage
  volumeName: datadir-mongodb-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mongodb-1
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  claimRef:
    name: datadir-mongodb-1
    namespace: mongodb
  local:
    path: /mnt/disks/mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker1
