apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}-exec
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}-exec
subjects:
  - kind: ServiceAccount
    name: drone-ci
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | trimSuffix "-" }}
  apiGroup: rbac.authorization.k8s.io
