---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-postgresql-ha-postgresql-0
  namespace: postgresql
spec:
  storageClassName: local-storage
  volumeName: data-postgresql-ha-postgresql-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-ha-postgresql-0
  namespace: postgresql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  claimRef:
    name: data-postgresql-ha-postgresql-0
    namespace: postgresql
  local:
    path: /mnt/disks/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-postgresql-ha-postgresql-1
  namespace: postgresql
spec:
  storageClassName: local-storage
  volumeName: data-postgresql-ha-postgresql-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-ha-postgresql-1
  namespace: postgresql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  claimRef:
    name: data-postgresql-ha-postgresql-1
    namespace: postgresql
  local:
    path: /mnt/disks/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker1
