apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wekan.fullname" . }}
  labels:
    app: {{ template "wekan.name" . }}
    chart: {{ template "wekan.chart" . }}
    component: wekan
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "wekan.name" . }}
      component: wekan
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "{{ .Values.vault.role }}"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        app: {{ template "wekan.name" . }}
        component: wekan
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "wekan.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ROOT_URL
              value: "{{ .Values.rootURL }}"
            - name: MONGO_URL
              value: "{{ .Values.mongoURL }}"
            - name: MONGO_OPLOG_URL
              value: "{{ .Values.mongoOplogURL }}"
            - name: MAIL_FROM
              value: {{ .Values.mailFrom | quote }}
            - name: MAIL_URL
              value: {{ .Values.mailURL | quote}}
          {{- range $key := .Values.env }}
          {{- if .value }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
