apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wekan.fullname" . }}
  labels:
    app: {{ template "wekan.name" . }}
    chart: {{ template "wekan.chart" . }}
    component: wekan
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  accessKey: {{ .Values.credentials.accessKey | b64enc }}
  secretKey: {{ .Values.credentials.secretKey | b64enc }}
