ingress-nginx:
  controller:
    name: controller
    replicaCount: 2
    resources:
      limits:
        cpu: "250m"
        memory: "500Mi"
      requests:
        cpu: "150m"
        memory: "250Mi"
    metrics:
      enabled: true
    service:
      enabled: true
      targetPorts:
        http: 80
        https: 443
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
    stats:
      enabled: true
  defaultBackend:
    enabled: true
    name: default-backend
    service:
      type: NodePort
  rbac:
    create: true
