drone:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "droneci"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  automountServiceAccountToken: true
  image:
    tag: 2.0.1
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: droneci.veriga.net
        paths:
          - "/"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    DRONE_LOGS_TRACE: "true"
    DRONE_SERVER_HOST: "droneci.veriga.net"
    DRONE_SERVER_PROTO: "https"
    DRONE_RPC_SECRET: "vault:secret/data/droneci/#rpc_secret"
    DRONE_GITHUB_CLIENT_ID: "vault:secret/data/droneci/#github_client_id"
    DRONE_GITHUB_CLIENT_SECRET: "vault:secret/data/droneci/#github_client_secret"
    DRONE_DATABASE_DRIVER: "postgres"
    DRONE_DATABASE_DATASOURCE: "vault:secret/data/droneci/#database_datasource"
    DRONE_USER_CREATE: "username:kelepirci,admin:true"
  persistentVolume:
    enabled: false