velero:
  backupsEnabled: true
  snapshotsEnabled: false
  image:
    imagePullSecrets:
      - name: registry
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-digitalocean
      image: digitalocean/velero-plugin:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  configuration:
    logLevel: debug
    provider: aws
    backupStorageLocation:
      name: veriga-backup
      bucket: veriga-backup
      provider: aws
      default: true
      config:
        region: nyc3
        s3Url: https://nyc3.digitaloceanspaces.com
        s3ForcePathStyle: true
  credentials:
    useSecret: true
    name: velero
    secretContents:
      cloud: |
        [default]
        aws_access_key_id=ZDEUE3BSE62LTECEWIZM
        aws_secret_access_key=947aWtA36pCwUBt9I06GS9lMI4JeK2W/Msw5GmKJpQw
  deployRestic: true
  restic:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
